import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`

        `}
      </style>
      <Head>
        <title>Max Fandom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <nav className={styles.mainnav}>
          <ul>
            <Link href='/' scroll={false}>
              <li>Home</li>
            </Link>
            <Link href='/about' scroll={false}>
              <li>About</li>
            </Link>
            <Link href='/contact' scroll={false}>
              <li>Contact</li>
            </Link>
            <Link href='/blogs' scroll={false}>
              <li>Blogs</li>
            </Link>
          </ul>
        </nav>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/logo.png"
            alt="maxfandom logo"
            width={274}
            height={200}
            priority
          />
        </div>

        <div className={styles.blogs}>
          <h2>Popular Blogs</h2>
          <div className={styles.blogItem}>
            <h3>Jason Todd: Robin Destroyed</h3>
            <p>Learn the tale of Jason Todd and how the opinion of fans changed the destiny of this character?</p>
          </div>
          <div className={styles.blogItem}>
            <h3>Black Knight: Cursed Avenger</h3>
            <p>Learn the tale of this lone crusader. Because his struggles are worth mentioning.</p>
          </div>
          <div className={styles.blogItem}>
            <h3>Avengers Arena & Heroes In Crisis</h3>
            <p>Blood was spilled. Lives were lost. And their world was never the same again.</p>
          </div>
          <div className={styles.blogItem}>
            <h3>Jon Kent: Destiny</h3>
            <p>Jonathan Kent – Son of Superman Let’s take a look at his journey and destiny.</p>
          </div>
        </div>

      </main>
    </div>
  );
}
