"use client";
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { Client,Databases,ID,Query } from 'appwrite';
import { useState,useEffect } from 'react';

const client = new Client();
const databases = new Databases(client);

client
  .setEndpoint('https://cloud.appwrite.io/v1')
  .setProject('maxfandom');

const inter = Inter({ subsets: ['latin'] });

// const blogItems = [
//   {
//     title: 'Jason Todd: Robin Destroyed',
//     image: '/blog1-bg.jpg',
//     author: 'John Doe',
//     image: '/blog1-image.jpg',
//     slug: 'jason-todd',
//   },
//   {
//     title: 'Black Knight: Cursed Avenger',
//     image: '/blog2-bg.jpg',
//     author: 'Jane Smith',
//     image: '/blog2-image.jpg',
//     slug: 'black-knight',
//   },
//   // ... other blog items
// ];

export default function Home() {

  const [blogItems,setblogItems] = useState([]);
  useEffect(() => {
    const databases = new Databases(client);

    let promise = databases.listDocuments(
      "649bfc2a05e1966040cc","649bfc37e73c9795de86",
    );

    promise.then(function (response) {
      console.log(response);
      setblogItems(response.documents);
    },function (error) {
      console.log(error);
    });
  },[]);

  return (
    <div className={styles.container}>
      <style jsx>
        {`

        `}
      </style>
      <Head>
        <title>Max Fandom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <nav className={styles.mainnav}>
          <ul>
            <Link href='/' scroll={false}>
              <li>Home</li>
            </Link>
            <Link href='/about' scroll={false}>
              <li>About</li>
            </Link>
            <Link href='/contact' scroll={false}>
              <li>Contact</li>
            </Link>
            <Link href='/blogs' scroll={false}>
              <li>Blogs</li>
            </Link>
          </ul>
        </nav>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/logo.png"
            alt="maxfandom logo"
            width={274}
            height={200}
            priority
          />
        </div>

        {/* <div className={styles.blogs}>
          <h2>Popular Blogs</h2>
          <div className={styles.blogItem}>
            <h3>Jason Todd: Robin Destroyed</h3>
            <p>Learn the tale of Jason Todd and how the opinion of fans changed the destiny of this character?</p>
          </div>
          <div className={styles.blogItem}>
            <h3>Black Knight: Cursed Avenger</h3>
            <p>Learn the tale of this lone crusader. Because his struggles are worth mentioning.</p>
          </div>
          <div className={styles.blogItem}>
            <h3>Avengers Arena & Heroes In Crisis</h3>
            <p>Blood was spilled. Lives were lost. And their world was never the same again.</p>
          </div>
          <div className={styles.blogItem}>
            <h3>Jon Kent: Destiny</h3>
            <p>Jonathan Kent – Son of Superman Let’s take a look at his journey and destiny.</p>
          </div>
        </div> */}
        
        <div className={styles.blogs}>
          <h2>Popular Blogs</h2>
          {blogItems.map((item) => (
            <div key={item.slug} className={styles.blogItem}>
              <div className={styles.blogItemImage}>
                <Image src={item.image} alt={item.title} width={500} height={300} />
              </div>
              <div className={styles.blogItemContent}>
                {item.title}
                <p>By {item.author}</p>
              </div>
              <div className={styles.metadesc}>
                {item.metadesc}
              </div>
              <div className={styles.readMore}>
                <Link href={`/blogs/${item.slug}`} className={styles.readMoreButton}>
                  Read More
                </Link>
              </div>
            </div>
          ))}
        </div>

      </main>
    </div>
  );
}
